server:
  port: 8080
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: BackEnd-BookStore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bookstore}
  data:
    redis:
      port: 6379
      host: localhost
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: yukihirayato2003@gmail.com
    password: lzrc ohon rqtz vhmo
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
app:
  jwt-key: 1ytvns7A2HHo2GUQ2d82xS2I7dRyWWv1BTU51Ve+il0
  aws:
    access-key-id:  ${SPRING_AWS_ACCESS_KEY_ID:_}
    secret-access-key: ${SPRING_AWS_SECRET_ACCESS_KEY:_}
    bucket:
      name: my-upload-for-essay
      request-timeout: 3600 # in seconds
  temp-folder: F:\tmp


  paypal:
    client-id: ${SPRING_PAYPAL_CLIENT_ID:AXjNIAvmyN7nqjWNdYrdjoX94D4vcaJ2LWHdXqz8qular76_jCvfH-uOSdCojCK-fgpo920v7bFA3Hm1}
    client-secret: ${SPRING_PAYPAL_CLIENT_SECRET:EIVotgOAxlAu80qDQnGxTWjKb_MsI0hxy-LsqlAzPWoQepxn_DmODeEDxVjYDIhyP_zmqOBye41xrXS-}
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG